//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraCuuThuatNgu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserHistory
    {
        public string Keyword { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.DateTime> DateModify { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual SearchHistory SearchHistory { get; set; }
    }
}
